### PR TITLE
Done

### PR DESCRIPTION
**Pull request by Njong392**
Done

### CODE REVIEW

**Review by elroykanye — COMMENTED** [review]
Will need some more clarification on this README update

**Review by elroykanye — CHANGES_REQUESTED** [review]
Maybe it's my observation but is there any logic to check if the username already exists?

**Review by elroykanye — COMMENTED** [review]
This is clear

**Review by elroykanye — CHANGES_REQUESTED** [review]
Consider using a more presentable dashboard even if the goal is just to reg or log

**Review by elroykanye — CHANGES_REQUESTED** [review]
Consider using a more presentable dashboard even if the goal is just to reg or log

**Comment by Njong392** [comment]
I'm really struggling with MySQL, the login file in my rep has a problem, I just don't know which. And no. I didn't check if a username already exists in the db

**Comment by Njong392** [comment]
> Maybe it's my observation but is there any logic to check if the username already exists?

There isn't 😑

**Comment by elroykanye** [comment]
Have you taken any course on it?

**Review by elroykanye — APPROVED** [review]
Something I can smile to at least

**Pull request merged**
